services:
  - type: web
    name: lamalux-pricing-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python loader.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
